folio-org/stripes-util

- lib/exportCsv.js
I found in testing that when `exportToCsv` was called by a dropdown, the download was not triggered. If called by a button, the download was triggered. @JohnC-80 suggested
> The first click might be swallowed by rootCloseWrapper's click to close the dropdown
This PR adds a 50ms delay to separate the clicks and successfully trigger the download.
> debounce click event

- lib/exportCsv.js
- package.json
I previously made the assumption that the first object in the array has all the fields. In the case of ui-requests, another object in the array may have additional fields. Rather than iterate over all the objects to find the set of unique fields, I added two new options:
- explicitlyIncludeFields: a list of known fields that may not be present on all objects and should be included
- onlyFields: an enumerated list of all fields that should be used
> refactor list transform

- CHANGELOG.md
- index.js
- package.json
Fixes 
```
WARNING in ./node_modules/@folio/requests/src/Requests.js 104:10-21
"export 'exportToCsv' was not found in '@folio/stripes/util' 
```
for https://issues.folio.org/browse/FOLIO-1547
Includes `v1.2.0` release.
> Export csv export

- CHANGELOG.md
- package.json
- Tested with sample "Hello World" UI app. No difference in bundle size but this will shake future unused code blocks.
> turned off sideEffects to enable tree-shaking

- CHANGELOG.md
- index.js
- package.json
- validators/README.md
- validators/index.js
- validators/required.js
As discussed on Slack recently, we really shouldn't be including copies of all the same redux-form validator functions in multiple UI modules. Here is the framework for providing them as part of stripes-util, including the first validator.
> Add validators

- CHANGELOG.md
- index.js
- lib/effectiveCallNumber.js
Utility function returns effective call number as a string given an item
record as returned from `/inventory/items/${item-id}`.
Refs [UIREQ-366](https://issues.folio.org/browse/UIREQ-366)
> UIREQ-366 format effective call number

- lib/effectiveCallNumber.js
Based on the comments in UIIN-750 it looks like when a prefix, suffix or callNumber are not present on the item record they should be inherited from the holdings record. This PR refactors effectiveCallNumber a bit to support that.
https://issues.folio.org/browse/STUTL-4
> Inherit values from holdings records for effectiveCallNumber. Part of STUTL-4

- lib/effectiveCallNumber.js
Based on the conversation with @marcjohnson-kint we learned that the `effectiveCallNumber` inheritance actually works correctly on the backend and we were using a wrong field. This PR is trying to address it.
https://issues.folio.org/browse/STUTL-4
> Use effectiveCallNumberComponents for prefix suffix and callNumber. Part of STUTL-4

- CHANGELOG.md
- lib/exportCsv.js
Add ability to turn on/off the headers adding to csv file. This feature is required in the scope of the [ticket](https://issues.folio.org/browse/UIDEXP-1).
> UIDEXP-1: Add configuration support to turn on/off headers adding to csv files

- index.js
- lib/escapeCqlValue.js
Provide a utility function to escape quotes `"` and backslashes `\` in
the values inserted into CQL queries.
Refs [UIIN-589](https://issues.folio.org/browse/UIIN-589)
> UIIN-589 utility function to escape CQL query values

- CHANGELOG.md
- lib/effectiveCallNumber.js
Fix a mistake in `effectiveCallNumber string` formatter, which @zburke noticed in https://github.com/folio-org/stripes-util/pull/30#discussion_r386680164 (thanks @zburke for being attentive!)
Also rewrite code with optional chaining syntax and remove lodash `get`
> UIU-1391: Fix mistake

- CHANGELOG.md
- package.json
Upgrade `react-intl` to `^4.5.3`. Whoops; missed this one when I did the
rest of the stripes-* updates.
Refs STRIPES-672.
> STRIPES-672 upgrade react-intl

- Jenkinsfile
Point sonarscan at `./lib` only, per https://folio-project.slack.com/archives/C210UCHQ9/p1612190962101400
> configure sonarscan narrowly

- CHANGELOG.md
- lib/exportCsv.js
- lib/exportCsv.test.js
When `exportCsv()` receives an array as a second argument, it
interprets that as a list of fields to exclude from the results.
However, it did not correctly check the type of the argument, preventing
this from ever happening.
Refs [STUTL-14](https://issues.folio.org/browse/STUTL-14)
> STUTL-14 exportCsv correctly handles legacy array implementation

- CHANGELOG.md
- lib/exportCsv.js
Show a console warning that `exportToCsv` is deprecated in this package and has
been moved to `stripes-components`.
Refs [STUTL-15](https://issues.folio.org/browse/STUTL-15)
> STUTL-15 show exportToCsv deprecation warning

- CHANGELOG.md
- lib/exportCsv.js
- lib/exportCsv.test.js
- package.json
`json2csv` was abandoned after v5. Updating to `@json2csv`, an ESM module, also required updating test infrastructure.
Refs [STUTL-30](https://issues.folio.org/browse/STUTL-30)
> STUTL-30 replace json2csv

- CHANGELOG.md
- lib/exportCsv.js
- lib/exportCsv.test.js
- package.json
Reverts folio-org/stripes-util#64
Maaaaaaybe this is the cause of failures in other repos, indicating that, across the board, jest needs to be updated to v29, and/or `@json2csv` needs to be added to `jest.config.js::transformIgnorePatterns`. I don't love either of those options, but I guess the "real" problem here is that @folio modules aren't transpiled upon distribution and that's allowing this issue to leak through.
> Revert "STUTL-30 replace json2csv"

- CHANGELOG.md
- index.js
- lib/getHeaderWithCredentials.js
- lib/getHeaderWithCredentials.test.js
Leverage cookie-based authentication in all API requests
https://issues.folio.org/browse/STUTL-32
> STUTL-32: Add getHeaderWithCredentials for leverage cookie-based authentication in all API requests

- CHANGELOG.md
- index.js
- lib/getSourceSuppressor.js
- lib/getSourceSuppressor.test.js
- test/jest/babel.config.js
https://issues.folio.org/browse/STUTL-34
Entries in a controlled vocabulary for some sources are not intended to be changed or deleted, only to be viewed. The `ui-inventory` app has a similar [util](https://github.com/folio-org/ui-inventory/blob/master/src/utils.js#L655) to suppress actions based on a source. To use this functionality in other applications, it will be useful to store it in a shared library.
Required by https://issues.folio.org/browse/UICONSET-21
> STUTL-34 Add `getSourceSuppressor` to build action suppressor based on an entry source

- CHANGELOG.md
- lib/escapeCqlValue.js
- lib/escapeCqlValue.test.js
Reverts folio-org/stripes-util#69
This appears to be a likely cause of > [150 e2e test failures](https://jenkins-aws.indexdata.com/job/Testing/job/Scheduled_Cypress_Tests/360/allure/) when tests rely on an asterisk as part of a wildcard search. We may eventually decide to keep this work, alongside a function that permits the asterisk, as outlined in [STUTL-37](https://issues.folio.org/browse/STUTL-37) / #73, but we'll want to rearrange the order of operations (implement that function, then convert existing search code to use that function, and only then implement the breaking change outlined in STUTL-33). 
FYI: @julianladisch
> Revert "STUTL-33: escapeCqlValue for " \ ^ * ?"

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
In CI, bump NodeJS from v16 to v18.
Refs [STUTL-39](https://issues.folio.org/browse/STUTL-39)
> STUTL-39 use NodeJS v18 in CI

- CHANGELOG.md
- package.json
Prune unused deps, including `engines.node`. This is a web application not a node application, thus, node is not a production dependency.
Refs [STUTL-41](https://issues.folio.org/browse/STUTL-41)
> STUTL-41 prune unused deps

- CHANGELOG.md
- index.js
- lib/escapeCqlValue.js
- lib/escapeCqlWildcards.js
- lib/escapeCqlWildcards.test.js
Implement a new function to escape [all five CQL wildcards](https://www.loc.gov/standards/sru/cql/contextSets/theCqlContextSet.html), instead of just two as was done in `escapeCqlValue()`:
* asterisk (*)
* question mark (?)
* caret (^)
* backslash (\)
* quote (")
Refs [STUTL-45](https://folio-org.atlassian.net/browse/STUTL-45), [STUTL-33](https://folio-org.atlassian.net/browse/STUTL-33)
> STUTL-45 implement escapeCqlWildcards

- .github/workflows/ui.yml
There is no module descriptor here. Additionally, make this workflow conditional to avoid running twice when GA logs multiple events for the same action when opening a new PR.
Refs [STUTL-47](https://folio-org.atlassian.net/browse/STUTL-47), [STRIPES-938](https://folio-org.atlassian.net/browse/STRIPES-938)
> STUTL-477 GA: omit publishing MD

- CHANGELOG.md
- lib/exportCsv.js
Related to https://github.com/folio-org/stripes-components/pull/2400
> STUTL-48 exportCSV - render download link to OverlayContainer rather than document.body

- CHANGELOG.md
- index.js
- lib/convertToSlipData.js
- lib/convertToSlipData.test.js
- package.json
Add convertToSlipData and supporting functions.
In settings -> circulation -> staff slips we create template that contain token. When we try print this template in our modules checkin, requests, requests-mediated and etc we need match real data and token from template. For this match responsibel convertToSlipData function and supporting functions. And in each of modules checkin, requests, requests-mediated and etc we have own exemplar of  convertToSlipData function and supporting functions. This mean that when we add new token in settings -> circulation -> staff slips we need updete convertToSlipData function in all modulel checkin, requests, requests-mediated and etc. For resolve this problem we want move convertToSlipData function and supporting functions to one plase and just reuse it …
> STUTL-51: Add convertToSlipData and supporting functions

- CHANGELOG.md
- lib/convertToSlipData.js
- lib/convertToSlipData.test.js
Update convertToSlipData and supporting functions
- In settings -> circulation -> staff slips we create template that contain token. When we try print this template in our modules checkin, requests, requests-mediated and etc we need match real data and token from template. For this match responsible convertToSlipData function and supporting functions. And in each of modules checkin, requests, requests-mediated and etc we have own exemplar of  convertToSlipData function and supporting functions. This mean that when we add new token in settings -> circulation -> staff slips we need updete convertToSlipData function in all modules checkin, requests, requests-mediated and etc. For resolve this problem we want move convertToSlipData function and supporting functions to one please and just …
> STUTL-55: Update convertToSlipData and supporting functions
